const path=require(`path`)
console.log(path.sep)
const filePath=path.join('/content/','subfolder','text.txt','test.txt')
console.log(filePath)
const base=path.basename(filePath)
console.log(base)
const absoulte=path.resolve(__filename,'content','subfolder','text.txt','test.txt')
console.log(absoulte)